import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cookies } from "next/headers";
import LogoutButton from "@/components/logout";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userData = (await cookies()).get("userData");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-between p-4 bg-gray-800 text-white">
          <Link href="/" className="text-lg font-bold">
            Mi Aplicación
          </Link>
          {userData ? (
            <div className="space-x-4">
              <Link href="/tasks" className="hover:text-gray-300">
                Dashboard
              </Link>
              <Link href="/profile" className="hover:text-gray-300">
                Profile
              </Link>
              <LogoutButton />
            </div>
          ) : (
            <div className="space-x-4">
              <Link href="/login" className="hover:text-gray-300">
                Login
              </Link>
              <Link href="/sign-up" className="hover:text-gray-300">
                Register
              </Link>
            </div>
          )}
        </nav>
        {children}
        <Toaster richColors position="top-center"/>
      </body>
    </html>
  );
}
